New gait slope up
project-march/gait-files pull request #119
Opened 2019-11-22 14:27 UTC by marnixbrands

## Description

Add Ramp and Door slope up gait 

## Changes
 Add gait files for the Ramp and Door slope up gait

2019-11-25 10:17 UTC, gaiavdh submitted a review, later dismissed

2019-11-25 10:39 UTC, Roelemans requested changes

2019-11-25 10:39 UTC, Roelemans commented on march_gait_files/airgait-v/default.yaml
> +                       right_close: MV_RD_slopeup_rightclose_v1, leftclose: MV_RD_slopeup_leftclose_v1}
```suggestion
                       right_close: MV_RD_slopeup_rightclose_v1, left_close: MV_RD_slopeup_leftclose_v1}
```

2019-11-26 14:48 UTC, Roelemans approved these changes

2019-11-26 14:48 UTC, merged