Add new version of walking gait with larger step size
project-march/gait-files pull request #123
Opened 2019-12-09 15:31 UTC by gaiavdh

## Description
 Add a new version of the walking gait that has a larger step size. Sjaan has indicated during the last training that she wants to try this, so I thought it would be nice if we have a version for the next training ready. In this version, only the hip flexion angles are adjusted - based on an earlier gait made by MARCH IV that had somewhat larger steps - nothing else has changed in the gait, as I think it is better to do this later, when we have analysed the gait and know how to change it. Also, I copied the (sub)gait files to the airgait-v folder.

## Changes
 Added a new version of the walking gait.

2019-12-09 16:55 UTC, Roelemans requested changes
You added a larger walking gait, but the version is "MV_walk_leftclose_v1" with no mention of the fact that it is larger. Maybe nice to add info on this? (so something like "MV_walk_leftclose_43_cm_v1").

> Also, I copied the (sub)gait files to the airgait-v folder. 
Don't you mean that you copied them to test-versions-v?

2019-12-09 18:03 UTC, gaiavdh commented
At the beginning of the year, we made a naming system for our gaits. The idea was that we would name all versions v1, v2, etc. On Confluence, we have made a quite extended overview of all versions and what has changed between them. Our reasoning behind this was that if you would document every change in the version name, these names will become very long. In this version, it is only the step size that has changed, but what if we change more: step height, add ankle movements, etc.? After two changes, the version name will be very long, and not fully describe all changes anymore. Moreover, we thought that if you name all versions with a number, it is very easy to just tell someone (e.g. during training) to use version 3, instead of "version 43-cm-length-and-even-higher-step" or something of the sort. I do agree with you that our naming system is not perfect either, and we are definitely open to discussion (both a version number and a description could maybe work?), but this is our reasoning behind it...

And no, I do not mean that I copied them to test_versions-v. I meant the second commit: I saved the gaits in the test_versions-v folder first, then tested it in the gait selection and simulation, and then copied it to airgait-v :)

2019-12-10 09:12 UTC, Roelemans commented
Ah okay, good that you already put thought into the naming system! I have a few suggestions, feel free to reject everything.

Swap around order of naming to put relevant things first, so: "v1(.0)_(43cm_)leftclose_walk_MV" (or swap walk and leftclose). Advantage is that you glean relevant info first, since you usually already know that you are in the walk -> leftclose folder. 
The extra .0 will allow you to iterate a bit within one version. For example you may have a few different versions of a "larger" step gait, a bit faster/slower, a bit more knee flexion etc. Then you can keep everything under v1 and iterate the .0
The 43cm will add easy read info for noobs.

2019-12-10 09:12 UTC, Roelemans approved these changes

2019-12-10 09:20 UTC, merged