Gait selection develop
project-march/gait-files pull request #212
Opened 2020-08-25 14:50 UTC by Olavhaasie

## Description
This PR adds the new features made possible by the new gait selection :tada: 

## Changes
* Gait graphs
* Named idle positions in gait files
* Removed home gaits, since they are now generated
* Add small and large subgaits to walk in minimal for size transitioning
* Every subgait version on a new line for easier version control
* Removed the old airgait, test_versions and training gait directories since they were no longer up to date and never used

2020-08-25 15:20 UTC, gaiavdh commented
The airgait, training and test_versions gait directories contain all the MARCH IV gaits. Are we sure we want to delete all the gaits they made? I think it could be nice for the new Movement Engineers to be able to take a look at what MARCH IV did. Not sure if anyone agrees on this? Or would it be a problem/inconvenient to keep them?

2020-08-25 15:40 UTC, Olavhaasie commented
> The airgait, training and test_versions gait directories contain all the MARCH IV gaits. Are we sure we want to delete all the gaits they made? I think it could be nice for the new Movement Engineers to be able to take a look at what MARCH IV did. Not sure if anyone agrees on this? Or would it be a problem/inconvenient to keep them?

Okay I wasn't aware that these were still used. We can keep them, however, they won't work with the gait selection right away, since that requires some changes. I think these gait directories are never used as gait directory, so that shouldn't be a problem. I could re-add them in a separate directory called `march-iv-gaits` or something like that. Then they can still be used with the gait generator, but not with the gait selection.

2020-08-25 15:47 UTC, gaiavdh commented
> > The airgait, training and test_versions gait directories contain all the MARCH IV gaits. Are we sure we want to delete all the gaits they made? I think it could be nice for the new Movement Engineers to be able to take a look at what MARCH IV did. Not sure if anyone agrees on this? Or would it be a problem/inconvenient to keep them?
> 
> Okay I wasn't aware that these were still used. We can keep them, however, they won't work with the gait selection right away, since that requires some changes. I think these gait directories are never used as gait directory, so that shouldn't be a problem. I could re-add them in a separate directory called `march-iv-gaits` or something like that. Then they can still be used with the gait generator, but not with the gait selection.

Yes that would be nice! I don't think it is necessary that they can be used with the gait selection, so just being able to open them in the gait generator should be fine.

2020-08-25 17:56 UTC, RutgerVanBeek commented
Have you considered letting gait directories only differ by their yaml and not have all gaits copied in different directories. Some gait versions are in there a couple of times now, which is redundant I think. Furthermore if you copy a version to multiple directories and then only change when mistakes can slip in easily.

2020-08-25 18:24 UTC, RutgerVanBeek requested changes
I think you should delete some home gaits.

2020-08-25 18:24 UTC, RutgerVanBeek commented on march_gait_files/airgait-v/default.yaml
> +    home_stand: MIV_final
These should be removed, right?

2020-08-25 18:24 UTC, RutgerVanBeek commented on march_gait_files/test_versions-v/default.yaml
> +  ramp_door_slope_up:
Here as well

2020-08-25 18:24 UTC, RutgerVanBeek commented on march_gait_files/training-v/default.yaml
> +    home_stand: MIV_final
+1

2020-08-26 08:22 UTC, Olavhaasie commented
> Have you considered letting gait directories only differ by their yaml and not have all gaits copied in different directories. Some gait versions are in there a couple of times now, which is redundant I think. Furthermore if you copy a version to multiple directories and then only change when mistakes can slip in easily.

I agree that would be better, however, the walk gait is different for minimal and the other gait directories, which I do not have a direct solution for.

2020-08-26 08:28 UTC, gaiavdh commented
> > Have you considered letting gait directories only differ by their yaml and not have all gaits copied in different directories. Some gait versions are in there a couple of times now, which is redundant I think. Furthermore if you copy a version to multiple directories and then only change when mistakes can slip in easily.
> 
> I agree that would be better, however, the walk gait is different for minimal and the other gait directories, which I do not have a direct solution for.

The reason that the walk gait is different in the minimal gait directory is simply that we have not changed it there. So there's not really a reason for that and it is not a problem if it would be the same. However, one issue I see with only changing the default is that the different gait directories are also there for safety reasons. We make sure that in training-v are only gaits that are tested and can therefore be used with Sjaan. In test_versions-v are sometimes test gaits that we do not want to use on the exoskeleton. Alhtough I agree that it would be easier to have the gaits all in one directory, that would be an issue...

2020-08-26 12:31 UTC, RutgerVanBeek commented
> The reason that the walk gait is different in the minimal gait directory is simply that we have not changed it there. So there's not really a reason for that and it is not a problem if it would be the same. However, one issue I see with only changing the default is that the different gait directories are also there for safety reasons. We make sure that in training-v are only gaits that are tested and can therefore be used with Sjaan. In test_versions-v are sometimes test gaits that we do not want to use on the exoskeleton. Alhtough I agree that it would be easier to have the gaits all in one directory, that would be an issue...

I would then extend the yaml to say which gaits are in the 'directory' or group as that is a better name in that case. You would still have to create a PR to add a gait to a directory. However it will be a PR of one line, so less would go wrong. Next to that, a version 4 stairs gait right open is the same in every directory/group.

2020-08-26 12:50 UTC, RutgerVanBeek approved these changes

2020-08-27 07:26 UTC, JorisWeeda approved these changes

2020-08-28 15:14 UTC, Roelemans approved these changes

2020-09-16 09:04 UTC, merged